services:
    sitesplat.BBCore.helper:
        class: sitesplat\BBCore\helper
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@ext.manager'
            - '@template'
            - '@user'
            - '@request'
            - '@log'
            - '@cache'
            - '%core.root_path%'

    sitesplat.BBCore.listener:
        class: sitesplat\BBCore\event\listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@controller.helper'
            - '@template'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@path_helper'
        tags:
            - { name: event.listener }

    sitesplat.BBCore.admin_listener:
        class: sitesplat\BBCore\event\admin_listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@template'
            - '@ext.manager'
            - '@cache'
            - '@file_downloader'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
